/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionRecord = IDL.Record({
  'topic' : IDL.Text,
  'duration' : IDL.Nat,
  'subject' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SessionRecord)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(SessionRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionRecord = IDL.Record({
    'topic' : IDL.Text,
    'duration' : IDL.Nat,
    'subject' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SessionRecord)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(SessionRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };